name: Continuous integration

on:
  push:
    branches:
      - main
      - ci
    tags:
      - '*'

jobs:

  docker-build:
    name: Package app as Docker image
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
        - spark_version: 3.2.1
          hadoop_version: 3.2
        - spark_version: 3.3.0
          hadoop_version: 3
    
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: datatok/spark

    steps:

      -
        name: Checkout
        uses: actions/checkout@v2
    
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      -
        name: Login to Github registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=edge,prefix=v${{ matrix.spark_version }}-,branch=main
            type=ref,enable=true,prefix=v${{ matrix.spark_version }}-,event=tag

      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: src
          push: true
          tags: "${{ steps.meta.outputs.tags }}"
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            BUILDKIT_INLINE_CACHE=1
            SPARK_VERSION=${{ matrix.spark_version }}
            HADOOP_VERSION=${{ matrix.hadoop_version }}
            SPARK_CDN=https://dlcdn.apache.org/spark